Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# 2D AND 3D
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# dtype
# np.array([1, 2, 3], dtype=float)
np.array([1, 2, 3], dtype=bool)

array([ True,  True,  True])

In [ ]:
# np.arange
# np.arange(1, 11)
np.arange(1, 11, 2)     # just like range in python

array([1, 3, 5, 7, 9])

In [10]:
# with reshape
# np.arange(1, 11).reshape(5, 2)
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# np.ones and np.zeros
# used in deep learning
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
# np.random
np.random.random((3, 4))

array([[0.58906195, 0.18493286, 0.31609945, 0.46806932],
       [0.31637832, 0.90262595, 0.09648091, 0.19701316],
       [0.5809596 , 0.7778646 , 0.94970188, 0.96981394]])

In [ ]:
# np.linspace
# linear space between two points
np.linspace(-10, 10, 10)  # (lower, upper, no of points)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])