Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# 2D AND 3D
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# dtype
# np.array([1, 2, 3], dtype=float)
np.array([1, 2, 3], dtype=bool)

array([ True,  True,  True])

In [6]:
# np.arange
# np.arange(1, 11)
np.arange(1, 11, 2)     # just like range in python

array([1, 3, 5, 7, 9])

In [7]:
# with reshape
# np.arange(1, 11).reshape(5, 2)
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
# np.ones and np.zeros
# used in deep learning
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# np.random
np.random.random((3, 4))

array([[0.318423  , 0.39050062, 0.50150732, 0.22773288],
       [0.30275903, 0.15991102, 0.91262267, 0.80297418],
       [0.35007897, 0.90330012, 0.7584639 , 0.26608486]])

In [11]:
# np.linspace
# linear space between two points
# np.linspace(-10, 10, 10)  # (lower, upper, no of points)
np.linspace(-10, 10, 10, dtype=int)  # (lower, upper, no of points)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [12]:
# np.identity
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Array Attributes

In [13]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
# ndim (no of dimension)
# a1.ndim
# a2.ndim
a3.ndim

3

In [15]:
# shape
# a1.shape
# a2.shape
a3.shape

(2, 2, 2)

In [16]:
# size
# a1.size
# a2.size
a3.size

8

In [17]:
# itemsize          # int32 -> 4 bytes, int64 -> 8 bytes
# a1.itemsize
# a2.itemsize
a3.itemsize

8

In [18]:
# dtype
# a1.dtype
a2.dtype
# a3.dtype

dtype('float64')

Changing Datatype

In [19]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [21]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations
# multiply by 2 with every element
# all arithmetic oprtrs
# a1 * 2
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational operators
# a2 > 15
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# a1 + a2
# a1 * a2
# a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [33]:
a1 = np.random.random((3, 3))
a1 = np.round(a1*100)
a1

array([[58., 20., 54.],
       [27., 37., 17.],
       [86., 99., 52.]])

In [40]:
# max/min/sum/prod
# np.max(a1)
# np.min(a1)
# np.sum(a1)
# np.prod(a1)
# np.max(a1, axis=1)   # 0 -> col, 1 -> row
np.max(a1, axis=0)

array([86., 99., 54.])

In [44]:
# mean/median/std/var
# np.mean(a1, axis=1)
# np.median(a1, axis=1)
# np.std(a1, axis=1)
np.var(a1, axis=1)

array([290.66666667,  66.66666667, 392.66666667])

In [45]:
# trigonometry
np.sin(a1)

array([[ 0.99287265,  0.91294525, -0.55878905],
       [ 0.95637593, -0.64353813, -0.96139749],
       [-0.92345845, -0.99920683,  0.98662759]])

In [46]:
# dot product
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [48]:
# log and exponents
# np.log(a1)
np.exp(a1)

array([[1.54553894e+25, 4.85165195e+08, 2.83075330e+23],
       [5.32048241e+11, 1.17191424e+16, 2.41549528e+07],
       [2.23524660e+37, 9.88903032e+42, 3.83100800e+22]])

In [56]:
# round/floor/ceil
# np.round(np.random.random((2, 3)) * 100)
# np.floor(np.random.random((2, 3)) * 100)
np.ceil(np.random.random((2, 3)) * 100)

array([[76.,  2., 44.],
       [27.,  6., 44.]])

Indexing and Slicing

In [68]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
# a1[-1]
a1[0]

np.int64(0)

In [71]:
# a2[1, 2]
# a2[2, 3]
a2[1, 0]

np.int64(4)

In [72]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
# a3[1, 0, 1]
# a3[0, 1, 0]
# a3[0, 0, 0]
a3[1, 1, 0]

np.int64(6)

In [77]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
# a1[2:5]
# a1[2:5:2]
# a1[1:8:2]
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [89]:
# a2[0,:]
a2[:,2]

array([ 2,  6, 10])