### np.sort

Return a sorted copy of an array.
https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
import numpy as np

a = np.random.randint(1, 100, 15)
a

array([66, 84,  3, 92, 94, 16, 49, 21, 34, 87, 54, 49, 90,  4, 25],
      dtype=int32)

In [3]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[88, 68, 51, 22],
       [ 7, 20, 14,  3],
       [12, 19, 27, 90],
       [99,  8, 62, 14],
       [64, 21, 67, 39],
       [50, 66, 30, 92]], dtype=int32)

In [4]:
# np.sort(a)
np.sort(a)[::-1]    # decreasing order

array([94, 92, 90, 87, 84, 66, 54, 49, 49, 34, 25, 21, 16,  4,  3],
      dtype=int32)

In [5]:
np.sort(b)

array([[22, 51, 68, 88],
       [ 3,  7, 14, 20],
       [12, 19, 27, 90],
       [ 8, 14, 62, 99],
       [21, 39, 64, 67],
       [30, 50, 66, 92]], dtype=int32)

In [6]:
# np.sort(b, axis=0)  # column wise sorting
np.sort(b, axis=0)[::-1]

array([[99, 68, 67, 92],
       [88, 66, 62, 90],
       [64, 21, 51, 39],
       [50, 20, 30, 22],
       [12, 19, 27, 14],
       [ 7,  8, 14,  3]], dtype=int32)

### np.append

The numpy.append() appends values along the metioned axis at the end of the array.

In [7]:
np.append(a, 200)

array([ 66,  84,   3,  92,  94,  16,  49,  21,  34,  87,  54,  49,  90,
         4,  25, 200])

In [8]:
b

array([[88, 68, 51, 22],
       [ 7, 20, 14,  3],
       [12, 19, 27, 90],
       [99,  8, 62, 14],
       [64, 21, 67, 39],
       [50, 66, 30, 92]], dtype=int32)

In [9]:
# np.append(b, np.ones((b.shape[0], 1)), axis=1)
np.append(b, np.random.random((b.shape[0], 1)), axis=1)

array([[88.        , 68.        , 51.        , 22.        ,  0.99723154],
       [ 7.        , 20.        , 14.        ,  3.        ,  0.66462142],
       [12.        , 19.        , 27.        , 90.        ,  0.24497317],
       [99.        ,  8.        , 62.        , 14.        ,  0.13626544],
       [64.        , 21.        , 67.        , 39.        ,  0.46495762],
       [50.        , 66.        , 30.        , 92.        ,  0.43972875]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [10]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
# np.concatenate((c, d), axis=0)    # row wise concat
np.concatenate((c, d), axis=1)      # column wise concat

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [16]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

print(e)


[1 1 2 2 3 3 4 4 5 5 6 6]


In [17]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [20]:
a.shape

(15,)

In [21]:
# np.expand_dims(a, axis=0)
np.expand_dims(a, axis=0).shape

(1, 15)

In [24]:
np.expand_dims(a, axis=1)
# np.expand_dims(a, axis=1).shape

array([[66],
       [84],
       [ 3],
       [92],
       [94],
       [16],
       [49],
       [21],
       [34],
       [87],
       [54],
       [49],
       [90],
       [ 4],
       [25]], dtype=int32)

### np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [28]:
a

array([66, 84,  3, 92, 94, 16, 49, 21, 34, 87, 54, 49, 90,  4, 25],
      dtype=int32)

In [31]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  3,  4,  9, 10, 12]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)      # np.where(condition,true,false)

array([ 0,  0,  3,  0,  0, 16, 49, 21, 34,  0,  0, 49,  0,  4, 25],
      dtype=int32)

In [33]:
# replace all even numbers with 0
np.where(a%2==0,0,a)

array([ 0,  0,  3,  0,  0,  0, 49, 21,  0, 87,  0, 49,  0,  0, 25],
      dtype=int32)

### np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [34]:
a

array([66, 84,  3, 92, 94, 16, 49, 21, 34, 87, 54, 49, 90,  4, 25],
      dtype=int32)

In [35]:
np.argmax(a)

np.int64(4)

In [36]:
b

array([[88, 68, 51, 22],
       [ 7, 20, 14,  3],
       [12, 19, 27, 90],
       [99,  8, 62, 14],
       [64, 21, 67, 39],
       [50, 66, 30, 92]], dtype=int32)

In [38]:
# np.argmax(b, axis=0)    # column wise
np.argmax(b, axis=1)    # row wise

array([0, 1, 3, 0, 2, 3])

In [40]:
np.argmin(a)

np.int64(2)

### np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [41]:
a

array([66, 84,  3, 92, 94, 16, 49, 21, 34, 87, 54, 49, 90,  4, 25],
      dtype=int32)

In [42]:
np.cumsum(a)

array([ 66, 150, 153, 245, 339, 355, 404, 425, 459, 546, 600, 649, 739,
       743, 768])

In [43]:
b

array([[88, 68, 51, 22],
       [ 7, 20, 14,  3],
       [12, 19, 27, 90],
       [99,  8, 62, 14],
       [64, 21, 67, 39],
       [50, 66, 30, 92]], dtype=int32)

In [47]:
# np.cumsum(b)    # converts 2d to 1d and thn gives cumsum
np.cumsum(b, axis=0)
# np.cumsum(b, axis=1)

array([[ 88,  68,  51,  22],
       [ 95,  88,  65,  25],
       [107, 107,  92, 115],
       [206, 115, 154, 129],
       [270, 136, 221, 168],
       [320, 202, 251, 260]])

In [ ]:
np.cumprod(a)   # product

array([                  66,                 5544,                16632,
                    1530144,            143833536,           2301336576,
               112765492224,        2368075336704,       80514561447936,
           7004766845970432,   378257409682403328,    87869000728211456,
        7908210065539031040, -5260647885262979072, -2388988615607615488])