Numpy array vs Python list

In [2]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []

import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)

7.0984086990356445


In [3]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.5119419097900391


In [4]:
7.09/0.51

13.901960784313726

In [5]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [10]:
# a = np.arange(10000000)
# a = np.arange(10000000, dtype=np.int32)
# a = np.arange(10000000, dtype=np.int16)
# a = np.arange(10000000, dtype=np.int8)
# sys.getsizeof(a)
a = np.arange(10000000, dtype=np.int8)

print(a[-10:])

[118 119 120 121 122 123 124 125 126 127]


In [ ]:
# convenience
# numpy is better than python list
# numpy takes less time, space and memory compared to python list
# more convenient to work with numpy

Advanced Indexing

In [13]:
# Fancy indexing
a = np.arange(24).reshape(6, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
# a[[0, 2, 3]]
# a[[0, 2, 3, 5]]
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [23]:
# Boolean indexing
# indexing based on condition
a = np.random.randint(1, 100, 24).reshape(6, 4)
a

array([[78, 18, 23, 98],
       [27, 56, 49, 27],
       [89,  5,  5, 51],
       [93,  5, 12, 29],
       [31, 49, 17, 24],
       [86, 73, 90, 61]], dtype=int32)

In [ ]:
# find all the numbers greater than 50
# a > 50
a[a > 50]   # give all no. greater than 50

array([78, 98, 56, 89, 51, 93, 86, 73, 90, 61], dtype=int32)

In [27]:
# find out even numbers
# a % 2 == 0
a[a % 2 == 0]

array([78, 18, 98, 56, 12, 24, 86, 90], dtype=int32)

In [29]:
# greater then 50 and even
# (a > 50) & (a % 2 == 0)
a[(a > 50) & (a % 2 == 0)]

array([78, 98, 56, 86, 90], dtype=int32)

In [31]:
# all numbers divisible by 7
# a[a % 7 == 0]
a[~(a % 7 == 0)]

array([78, 18, 23, 27, 27, 89,  5,  5, 51, 93,  5, 12, 29, 31, 17, 24, 86,
       73, 90, 61], dtype=int32)

Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
The smaller array is "broadcast" across the larger array so that they have compatible shapes.