### np.sort

Return a sorted copy of an array.
https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [3]:
import numpy as np

a = np.random.randint(1, 100, 15)
a

array([46, 61, 49,  6, 61, 19, 10, 27, 86, 48, 58, 68, 66,  4, 90],
      dtype=int32)

In [4]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[25, 86,  9, 29],
       [90, 95, 52, 93],
       [47,  4, 30,  8],
       [18, 71, 28, 97],
       [49, 47, 78, 57],
       [21, 44, 51, 96]], dtype=int32)

In [ ]:
# np.sort(a)
np.sort(a)[::-1]    # decreasing order

array([90, 86, 68, 66, 61, 61, 58, 49, 48, 46, 27, 19, 10,  6,  4],
      dtype=int32)

In [6]:
np.sort(b)

array([[ 9, 25, 29, 86],
       [52, 90, 93, 95],
       [ 4,  8, 30, 47],
       [18, 28, 71, 97],
       [47, 49, 57, 78],
       [21, 44, 51, 96]], dtype=int32)

In [9]:
# np.sort(b, axis=0)  # column wise sorting
np.sort(b, axis=0)[::-1]

array([[90, 95, 78, 97],
       [49, 86, 52, 96],
       [47, 71, 51, 93],
       [25, 47, 30, 57],
       [21, 44, 28, 29],
       [18,  4,  9,  8]], dtype=int32)

### np.append

The numpy.append() appends values along the metioned axis at the end of the array.

In [11]:
np.append(a, 200)

array([ 46,  61,  49,   6,  61,  19,  10,  27,  86,  48,  58,  68,  66,
         4,  90, 200])

In [12]:
b

array([[25, 86,  9, 29],
       [90, 95, 52, 93],
       [47,  4, 30,  8],
       [18, 71, 28, 97],
       [49, 47, 78, 57],
       [21, 44, 51, 96]], dtype=int32)

In [16]:
# np.append(b, np.ones((b.shape[0], 1)), axis=1)
np.append(b, np.random.random((b.shape[0], 1)), axis=1)

array([[2.50000000e+01, 8.60000000e+01, 9.00000000e+00, 2.90000000e+01,
        4.52963990e-01],
       [9.00000000e+01, 9.50000000e+01, 5.20000000e+01, 9.30000000e+01,
        7.72368722e-02],
       [4.70000000e+01, 4.00000000e+00, 3.00000000e+01, 8.00000000e+00,
        8.73952874e-02],
       [1.80000000e+01, 7.10000000e+01, 2.80000000e+01, 9.70000000e+01,
        4.38032207e-01],
       [4.90000000e+01, 4.70000000e+01, 7.80000000e+01, 5.70000000e+01,
        3.68765452e-01],
       [2.10000000e+01, 4.40000000e+01, 5.10000000e+01, 9.60000000e+01,
        8.01535331e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.