Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
# 2D AND 3D
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# dtype
# np.array([1, 2, 3], dtype=float)
np.array([1, 2, 3], dtype=bool)

array([ True,  True,  True])

In [5]:
# np.arange
# np.arange(1, 11)
np.arange(1, 11, 2)     # just like range in python

array([1, 3, 5, 7, 9])

In [6]:
# with reshape
# np.arange(1, 11).reshape(5, 2)
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
# np.ones and np.zeros
# used in deep learning
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# np.random
np.random.random((3, 4))

array([[0.07837461, 0.49818952, 0.35505194, 0.53278669],
       [0.5874014 , 0.75065583, 0.39654341, 0.51332073],
       [0.46840623, 0.77705231, 0.18678659, 0.99249956]])

In [10]:
# np.linspace
# linear space between two points
# np.linspace(-10, 10, 10)  # (lower, upper, no of points)
np.linspace(-10, 10, 10, dtype=int)  # (lower, upper, no of points)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [11]:
# np.identity
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Array Attributes

In [12]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
# ndim (no of dimension)
# a1.ndim
# a2.ndim
a3.ndim

3

In [14]:
# shape
# a1.shape
# a2.shape
a3.shape

(2, 2, 2)

In [15]:
# size
# a1.size
# a2.size
a3.size

8

In [16]:
# itemsize          # int32 -> 4 bytes, int64 -> 8 bytes
# a1.itemsize
# a2.itemsize
a3.itemsize

8

In [17]:
# dtype
# a1.dtype
a2.dtype
# a3.dtype

dtype('float64')

Changing Datatype

In [18]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [19]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
# scalar operations
# multiply by 2 with every element
# all arithmetic oprtrs
# a1 * 2
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [21]:
# relational operators
# a2 > 15
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
# vector operations
# a1 + a2
# a1 * a2
# a1 ** a2

Array Functions

In [23]:
a1 = np.random.random((3, 3))
a1 = np.round(a1*100)
a1

array([[87., 38., 69.],
       [36., 75., 24.],
       [75., 62., 25.]])

In [24]:
# max/min/sum/prod
# np.max(a1)
# np.min(a1)
# np.sum(a1)
# np.prod(a1)
# np.max(a1, axis=1)   # 0 -> col, 1 -> row
np.max(a1, axis=0)

array([87., 75., 69.])

In [25]:
# mean/median/std/var
# np.mean(a1, axis=1)
# np.median(a1, axis=1)
# np.std(a1, axis=1)
np.var(a1, axis=1)

array([409.55555556, 474.        , 448.66666667])

In [26]:
# trigonometry
np.sin(a1)

array([[-0.82181784,  0.29636858, -0.11478481],
       [-0.99177885, -0.38778164, -0.90557836],
       [-0.38778164, -0.7391807 , -0.13235175]])

In [27]:
# dot product
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [28]:
# log and exponents
# np.log(a1)
np.exp(a1)

array([[6.07603023e+37, 3.18559318e+16, 9.25378173e+29],
       [4.31123155e+15, 3.73324200e+32, 2.64891221e+10],
       [3.73324200e+32, 8.43835667e+26, 7.20048993e+10]])

In [29]:
# round/floor/ceil
# np.round(np.random.random((2, 3)) * 100)
# np.floor(np.random.random((2, 3)) * 100)
np.ceil(np.random.random((2, 3)) * 100)

array([[84.,  4., 76.],
       [62.,  5.,  9.]])

Indexing and Slicing

In [30]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
# a1[-1]
a1[0]

np.int64(0)

In [32]:
# a2[1, 2]
# a2[2, 3]
a2[1, 0]

np.int64(4)

In [33]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
# a3[1, 0, 1]
# a3[0, 1, 0]
# a3[0, 0, 0]
a3[1, 1, 0]

np.int64(6)

In [35]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# a1[2:5]
# a1[2:5:2]
# a1[1:8:2]
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# a2[0,:]
a2[:,2]

array([0, 1, 2, 3])

In [37]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [38]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [47]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [49]:
a2[1, ::3]

array([4, 7])

In [54]:
a2[:2, 1::2]

array([[1, 3],
       [5, 7]])

In [56]:
a3 = np.arange(27).reshape(3, 3, 3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [58]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [60]:
a3[0,1]

array([3, 4, 5])

In [63]:
a3[1,:3,1]

array([10, 13, 16])

In [65]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [68]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [72]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [70]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [71]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [74]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [75]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [76]:
# Transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [78]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [81]:
# ravel
# a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [83]:
# horizontal stacking
a4 = np.arange(12).reshape(3, 4)
a5 = np.arange(12, 24).reshape(3, 4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
np.hstack((a4, a5, a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [86]:
# verical stacking
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [87]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [92]:
# verical splitting
# a5
np.vsplit(a5, 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]